# ==============================
# CONFIGURACIÓN GENERAL DEL SITIO
# ==============================
title: "Academia del Vallenato Cartagena"
description: "Aprende vallenato en la Academia del Vallenato Cartagena. Clases de acordeón, caja y guacharaca. Venta de instrumentos y servicios de música en vivo."
baseurl: ""  # No modificar si se publica en la raíz del dominio
url: "https://www.academiadelvallenatocartagena.com"

# ==============================
# CONFIGURACIÓN DE JEKYLL / GITHUB PAGES
# ==============================
theme: null
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# ==============================
# METADATOS PERSONALIZADOS
# ==============================
academia:
  name: "Academia del Vallenato Cartagena"
  founded: 2010
  location: "Cartagena, Colombia"
  email: "info@academiadelvallenatocartagena.com"
  phone: "+57 300 123 4567"

# ==============================
# CONFIGURACIÓN DE SEO
# ==============================
google_analytics: null   # Agrega tu ID (ej: UA-XXXXX-Y o G-XXXXXXXXXX) si usas GA
lang: "es"
timezone: "America/Bogota"

# ==============================
# OPCIONES DE BUILD Y RENDIMIENTO
# ==============================
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json

# ==============================
# CONFIGURACIÓN DEL SITEMAP
# ==============================
sitemap:
  filename: "sitemap.xml"
  exclude:
    - "/404.html"
